import { Plant } from './types';

const rawPlants: Plant[] = [
  // General Indoor
  { id: '1', name: 'Snake Plant', scientificName: 'Sansevieria trifasciata', price: 200, originalPrice: 299, rating: 4.8, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Air purifier, very low maintenance.', image: '',  stock: 24, description: 'The Snake Plant is one of the most popular and hardy houseplants.' },
  { id: '2', name: 'Money Plant (Pothos)', scientificName: 'Epipremnum aureum', price: 499, originalPrice: 700, rating: 4.7, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Good luck plant, grows in water or soil.', image: '',  stock: 30, description: 'A versatile climber that is incredibly easy to grow.' },
  { id: '3', name: 'Spider Plant', scientificName: 'Chlorophytum comosum', price: 449, originalPrice: 600, rating: 4.6, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Easy to grow, good for beginners.', image: '',  stock: 15, description: 'Known for its spider-like plantlets that hang down from the mother plant.' },
  { id: '4', name: 'ZZ Plant', scientificName: 'Zamioculcas zamiifolia', price: 1299, originalPrice: 1800, rating: 4.9, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Grows well in low light.', image: '',  stock: 12, description: 'A slow-growing plant with waxy, green leaves.' },
  { id: '5', name: 'Peace Lily', scientificName: 'Spathiphyllum', price: 899, originalPrice: 1300, rating: 4.7, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Removes indoor toxins.', image: '',  stock: 20, description: 'Beautiful white blooms and dark green leaves.' },
  { id: '6', name: 'Areca Palm', scientificName: 'Dypsis lutescens', price: 1599, originalPrice: 2200, rating: 4.8, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Natural air humidifier.', image: '',  stock: 10, description: 'A popular indoor palm with feathery fronds.' },
  { id: '7', name: 'Rubber Plant', scientificName: 'Ficus elastica', price: 1199, originalPrice: 1600, rating: 4.7, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Attractive large leaves.', image: '',  stock: 18, description: 'Stunning dark green leaves with a glossy finish.' },
  { id: '8', name: 'Aloe Vera', scientificName: 'Aloe barbadensis miller', price: 399, originalPrice: 550, rating: 4.9, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Medicinal and air-purifying.', image: '',  stock: 40, description: 'A succulent known for its medicinal properties.' },
  { id: '9', name: 'Bamboo Palm', scientificName: 'Chamaedorea seifrizii', price: 1499, originalPrice: 2000, rating: 4.6, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Filters formaldehyde and xylene', image: '',  stock: 15, description: 'Adds a tropical feel to any room.' },
  { id: '10', name: 'English Ivy', scientificName: 'Hedera helix', price: 549, originalPrice: 800, rating: 4.5, category: 'Indoor', subCategory: 'General Indoor', benefits: 'Reduces airborne fecal matter', image: '',  stock: 25, description: 'A classic climbing or trailing plant.' },

  // Decorative Indoor Plants
  { id: '11', name: 'Chinese Evergreen', scientificName: 'Aglaonema', price: 999, originalPrice: 1400, rating: 4.7, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Tolerates low light, air purifier', image: '',  stock: 20, description: 'Stunning variegated leaves.' },
  { id: '12', name: 'Croton', scientificName: 'Codiaeum variegatum', price: 799, originalPrice: 1100, rating: 4.6, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Vibrant colors boost mood', image: '',  stock: 15, description: 'Known for its colorful foliage.' },
  { id: '13', name: 'Monstera', scientificName: 'Monstera deliciosa', price: 1899, originalPrice: 2500, rating: 4.9, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Iconic look, large oxygen producer', image: '',  stock: 12, description: 'The famous Swiss Cheese plant.' },
  { id: '14', name: 'Philodendron', scientificName: 'Philodendron', price: 699, originalPrice: 950, rating: 4.7, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Easy to propagate, air cleaner', image: '',  stock: 30, description: 'A diverse genus of beautiful plants.' },
  { id: '15', name: 'Ficus Benjamina', scientificName: 'Ficus benjamina', price: 1399, originalPrice: 1900, rating: 4.5, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Elegant tree-like form', image: '',  stock: 10, description: 'Also known as the Weeping Fig.' },
  { id: '16', name: 'Dracaena', scientificName: 'Dracaena', price: 1199, originalPrice: 1600, rating: 4.6, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Removes benzene and lead', image: '',  stock: 18, description: 'Architectural and easy to care for.' },
  { id: '17', name: 'Cordyline', scientificName: 'Cordyline fruticosa', price: 899, originalPrice: 1250, rating: 4.4, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Colorful tropical vibes', image: '',  stock: 14, description: 'Often called the Ti plant.' },
  { id: '18', name: 'Calathea', scientificName: 'Calathea', price: 1499, originalPrice: 2100, rating: 4.8, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Pet friendly, stunning patterns', image: '',  stock: 12, description: 'Known for its "praying" leaves.' },
  { id: '19', name: 'Maranta (Prayer Plant)', scientificName: 'Maranta leuconeura', price: 749, originalPrice: 1000, rating: 4.7, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Fascinating leaf movement', image: '',  stock: 22, description: 'Leaves fold up at night like hands in prayer.' },
  { id: '20', name: 'Dieffenbachia', scientificName: 'Dieffenbachia', price: 849, originalPrice: 1150, rating: 4.5, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Large, lush foliage', image: '',  stock: 16, description: 'Commonly known as Dumb Cane.' },

  // Fern & Leaf Plants
  { id: '21', name: 'Boston Fern', scientificName: 'Nephrolepis exaltata', price: 649, originalPrice: 900, rating: 4.6, category: 'Indoor', subCategory: 'Fern & Leaf', benefits: 'High humidity booster', image: '',  stock: 20, description: 'Classic fern with feathery fronds.' },
  { id: '22', name: 'Maidenhair Fern', scientificName: 'Adiantum', price: 799, originalPrice: 1100, rating: 4.4, category: 'Indoor', subCategory: 'Fern & Leaf', benefits: 'Delicate beauty', image: '',  stock: 12, description: 'Known for its fragile, dainty leaves.' },
  { id: '23', name: 'Kimberly Queen Fern', scientificName: 'Nephrolepis obliterata', price: 899, originalPrice: 1200, rating: 4.7, category: 'Indoor', subCategory: 'Fern & Leaf', benefits: 'More sun tolerant than Boston fern', image: '',  stock: 15, description: 'Upright and elegant fern.' },
  { id: '24', name: 'Asparagus Fern', scientificName: 'Asparagus aethiopicus', price: 549, originalPrice: 750, rating: 4.5, category: 'Indoor', subCategory: 'Fern & Leaf', benefits: 'Fast growing, lacy look', image: '',  stock: 25, description: 'Not a true fern, but looks like one.' },
  { id: '25', name: 'Staghorn Fern', scientificName: 'Platycerium', price: 1699, originalPrice: 2300, rating: 4.9, category: 'Indoor', subCategory: 'Fern & Leaf', benefits: 'Unique wall-mounted decor', image: '',  stock: 8, description: 'Epiphytic fern that grows on trees or boards.' },

  // Succulent Indoor Plants
  { id: '26', name: 'Jade Plant', scientificName: 'Crassula ovata', price: 499, originalPrice: 700, rating: 4.8, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Considered lucky plant.', image: '',  stock: 35, description: 'A long-lived succulent with thick leaves.' },
  { id: '27', name: 'Haworthia', scientificName: 'Haworthiopsis fasciata', price: 349, originalPrice: 500, rating: 4.7, category: 'Indoor', subCategory: 'Succulent', benefits: 'Compact, perfect for desks', image: '',  stock: 40, description: 'Often called the Zebra Cactus.' },
  { id: '28', name: 'Kalanchoe', scientificName: 'Kalanchoe blossfeldiana', price: 599, originalPrice: 850, rating: 4.6, category: 'Indoor', subCategory: 'Succulent', benefits: 'Long-lasting colorful blooms', image: '',  stock: 20, description: 'A flowering succulent.' },
  { id: '29', name: 'Echeveria', scientificName: 'Echeveria', price: 299, originalPrice: 450, rating: 4.8, category: 'Indoor', subCategory: 'Succulent', benefits: 'Beautiful rosette shape', image: '',  stock: 50, description: 'Comes in many colors and sizes.' },
  { id: '30', name: 'Crassula', scientificName: 'Crassula', price: 399, originalPrice: 550, rating: 4.5, category: 'Indoor', subCategory: 'Succulent', benefits: 'Easy to maintain', image: '',  stock: 30, description: 'A diverse genus of succulents.' },

  // Flowering Indoor Plants
  { id: '31', name: 'Anthurium', scientificName: 'Anthurium andraeanum', price: 1299, originalPrice: 1800, rating: 4.8, category: 'Indoor', subCategory: 'Flowering', benefits: 'Blooms all year round', image: '',  stock: 15, description: 'Known for its waxy, heart-shaped flowers.' },
  { id: '32', name: 'Begonia', scientificName: 'Begonia', price: 699, originalPrice: 950, rating: 4.6, category: 'Indoor', subCategory: 'Flowering', benefits: 'Stunning leaf and flower variety', image: '',  stock: 20, description: 'Great for adding color indoors.' },
  { id: '33', name: 'African Violet', scientificName: 'Saintpaulia', price: 449, originalPrice: 650, rating: 4.7, category: 'Indoor', subCategory: 'Flowering', benefits: 'Compact and colorful', image: '',  stock: 25, description: 'Classic indoor flowering plant.' },
  { id: '34', name: 'Orchid', scientificName: 'Orchidaceae', price: 2499, originalPrice: 3500, rating: 4.9, category: 'Indoor', subCategory: 'Flowering', benefits: 'Elegant and long-lasting blooms', image: '',  stock: 10, description: 'The pinnacle of floral elegance.' },
  { id: '35', name: 'Bromeliad', scientificName: 'Bromeliaceae', price: 1199, originalPrice: 1700, rating: 4.7, category: 'Indoor', subCategory: 'Flowering', benefits: 'Tropical look, air purifier', image: '',  stock: 18, description: 'Unique central flower spike.' },

  // Indoor Herb Plants
  { id: '36', name: 'Mint', scientificName: 'Mentha', price: 199, originalPrice: 300, rating: 4.8, category: 'Indoor', subCategory: 'Indoor Herbs (Very Cheap)', benefits: 'Fresh scent, culinary use', image: '',  stock: 50, description: 'Easy to grow in a sunny window.' },
  { id: '37', name: 'Basil', scientificName: 'Ocimum basilicum', price: 149, originalPrice: 250, rating: 4.7, category: 'Indoor', subCategory: 'Indoor Herbs (Very Cheap)', benefits: 'Essential for cooking', image: '',  stock: 60, description: 'A must-have for any kitchen.' },
  { id: '38', name: 'Rosemary', scientificName: 'Salvia rosmarinus', price: 299, originalPrice: 450, rating: 4.6, category: 'Indoor', subCategory: 'Indoor Herbs (Very Cheap)', benefits: 'Aromatic and hardy', image: '',  stock: 30, description: 'Great for roasting and decor.' },
  { id: '39', name: 'Thyme', scientificName: 'Thymus vulgaris', price: 199, originalPrice: 300, rating: 4.5, category: 'Indoor', subCategory: 'Indoor Herbs (Very Cheap)', benefits: 'Versatile herb', image: '',  stock: 40, description: 'Low-growing and fragrant.' },
  { id: '40', name: 'Oregano', scientificName: 'Origanum vulgare', price: 249, originalPrice: 350, rating: 4.6, category: 'Indoor', subCategory: 'Indoor Herbs (Very Cheap)', benefits: 'Pizza and pasta essential', image: '',  stock: 35, description: 'Pungent and flavorful.' },

  // Small Desk Plants
  { id: '41', name: 'Lucky Bamboo', scientificName: 'Dracaena sanderiana', price: 599, originalPrice: 850, rating: 4.8, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Easy decorative plant.', image: '',  stock: 30, description: 'Grows in water or soil.' },
  { id: '42', name: 'Fittonia (Nerve Plant)', scientificName: 'Fittonia albivenis', price: 399, originalPrice: 600, rating: 4.7, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Beautiful vein patterns', image: '',  stock: 25, description: 'Loves high humidity.' },
  { id: '43', name: 'Pilea Peperomioides', scientificName: 'Pilea peperomioides', price: 699, originalPrice: 950, rating: 4.9, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Unique pancake-shaped leaves', image: '',  stock: 20, description: 'Also known as the Chinese Money Plant.' },
  { id: '44', name: 'Peperomia', scientificName: 'Peperomia', price: 449, originalPrice: 650, rating: 4.7, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Compact and diverse', image: '',  stock: 35, description: 'Many varieties to choose from.' },
  { id: '45', name: 'Polka Dot Plant', scientificName: 'Hypoestes phyllostachya', price: 349, originalPrice: 500, rating: 4.6, category: 'Indoor', subCategory: 'Small Indoor Plants', benefits: 'Splashes of color', image: '',  stock: 40, description: 'Known for its spotted leaves.' },

  // Other Indoor Plants
  { id: '46', name: 'Dwarf Date Palm', scientificName: 'Phoenix roebelenii', price: 2999, originalPrice: 4000, rating: 4.8, category: 'Indoor', subCategory: 'Other', benefits: 'Stately appearance', image: '',  stock: 5, description: 'A slow-growing palm.' },
  { id: '47', name: 'Parlor Palm', scientificName: 'Chamaedorea elegans', price: 899, originalPrice: 1300, rating: 4.7, category: 'Indoor', subCategory: 'Other', benefits: 'Classic Victorian favorite', image: '',  stock: 20, description: 'Very tolerant of low light.' },
  { id: '48', name: 'Kentia Palm', scientificName: 'Howea forsteriana', price: 4999, originalPrice: 7000, rating: 4.9, category: 'Indoor', subCategory: 'Other', benefits: 'Extremely durable and elegant', image: '',  stock: 3, description: 'The ultimate luxury palm.' },
  { id: '49', name: 'Elephant Ear Plant', scientificName: 'Alocasia/Colocasia', price: 1599, originalPrice: 2200, rating: 4.6, category: 'Indoor', subCategory: 'Other', benefits: 'Massive statement leaves', image: '',  stock: 10, description: 'Dramatic and tropical.' },
  { id: '50', name: 'Bird of Paradise', scientificName: 'Strelitzia reginae', price: 2499, originalPrice: 3500, rating: 4.9, category: 'Indoor', subCategory: 'Other', benefits: 'Spectacular flowers', image: '',  stock: 8, description: 'Iconic tropical plant.' },
  { id: '51', name: 'Yucca Plant', scientificName: 'Yucca elephantipes', price: 1299, originalPrice: 1800, rating: 4.5, category: 'Indoor', subCategory: 'Other', benefits: 'Very hardy and drought tolerant', image: '',  stock: 15, description: 'Sword-like leaves on a sturdy trunk.' },
  { id: '52', name: 'Schefflera', scientificName: 'Schefflera arboricola', price: 999, originalPrice: 1400, rating: 4.6, category: 'Indoor', subCategory: 'Other', benefits: 'Umbrella-like leaf clusters', image: '',  stock: 18, description: 'Commonly called the Umbrella Tree.' },
  { id: '53', name: 'Tradescantia', scientificName: 'Tradescantia zebrina', price: 499, originalPrice: 750, rating: 4.7, category: 'Indoor', subCategory: 'Other', benefits: 'Beautiful purple trailing leaves', image: '',  stock: 30, description: 'Fast growing and easy to propagate.' },
  { id: '54', name: 'Hoya', scientificName: 'Hoya carnosa', price: 1199, originalPrice: 1600, rating: 4.8, category: 'Indoor', subCategory: 'Other', benefits: 'Waxy leaves and fragrant flowers', image: '',  stock: 12, description: 'Also known as the Wax Plant.' },
  { id: '55', name: 'String of Pearls', scientificName: 'Senecio rowleyanus', price: 899, originalPrice: 1300, rating: 4.7, category: 'Indoor', subCategory: 'Other', benefits: 'Unique bead-like foliage', image: '',  stock: 15, description: 'A stunning trailing succulent.' },
  { id: '56', name: 'String of Hearts', scientificName: 'Ceropegia woodii', price: 999, originalPrice: 1400, rating: 4.8, category: 'Indoor', subCategory: 'Other', benefits: 'Heart-shaped leaves', image: '',  stock: 14, description: 'A delicate and romantic trailer.' },
  { id: '57', name: 'Rhipsalis Cactus', scientificName: 'Rhipsalis', price: 799, originalPrice: 1100, rating: 4.6, category: 'Indoor', subCategory: 'Other', benefits: 'Unique jungle cactus', image: '',  stock: 20, description: 'Epiphytic cactus with trailing stems.' },
  { id: '58', name: 'Lipstick Plant', scientificName: 'Aeschynanthus radicans', price: 849, originalPrice: 1200, rating: 4.7, category: 'Indoor', subCategory: 'Other', benefits: 'Vibrant red tubular flowers', image: '',  stock: 16, description: 'Loves bright indirect light.' },
  { id: '59', name: 'Alocasia', scientificName: 'Alocasia', price: 1499, originalPrice: 2100, rating: 4.8, category: 'Indoor', subCategory: 'Other', benefits: 'Exotic leaf shapes', image: '',  stock: 12, description: 'Highly sought-after tropicals.' },
  { id: '60', name: 'Syngonium', scientificName: 'Syngonium podophyllum', price: 549, originalPrice: 800, rating: 4.7, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Arrowhead-shaped leaves', image: '',  stock: 25, description: 'Versatile and easy to grow.' },
  { id: '61', name: 'Coleus', scientificName: 'Coleus scutellarioides', price: 349, originalPrice: 500, rating: 4.6, category: 'Indoor', subCategory: 'Decorative Indoor Plants', benefits: 'Vibrant foliage colors', image: '',  stock: 20, description: 'Known for its highly decorative and colorful leaves.' },

  // Outdoor Plants
  { id: '101', name: 'Rose', scientificName: 'Rosa', price: 599, originalPrice: 850, rating: 4.9, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Beautiful fragrance and colors', image: '',  stock: 50, description: 'The classic symbol of love and beauty.' },
  { id: '102', name: 'Marigold', scientificName: 'Tagetes', price: 149, originalPrice: 250, rating: 4.7, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Pest repellent and bright colors', image: '',  stock: 100, description: 'Easy to grow and very hardy.' },
  { id: '103', name: 'Hibiscus', scientificName: 'Hibiscus rosa-sinensis', price: 499, originalPrice: 750, rating: 4.8, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Large, showy tropical blooms', image: '',  stock: 30, description: 'Brings a tropical feel to any garden.' },
  { id: '104', name: 'Jasmine', scientificName: 'Jasminum', price: 399, originalPrice: 600, rating: 4.9, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Intense sweet fragrance', image: '',  stock: 40, description: 'A beautiful climbing vine.' },
  { id: '105', name: 'Lavender', scientificName: 'Lavandula', price: 449, originalPrice: 650, rating: 4.8, category: 'Outdoor', subCategory: 'Fragrant', benefits: 'Calming scent and bee-friendly', image: '',  stock: 35, description: 'Known for its soothing aroma.' },
  { id: '106', name: 'Sunflower', scientificName: 'Helianthus annuus', price: 199, originalPrice: 350, rating: 4.7, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Attracts pollinators, edible seeds', image: '',  stock: 60, description: 'Follows the sun across the sky.' },
  { id: '107', name: 'Tulips', scientificName: 'Tulipa', price: 699, originalPrice: 950, rating: 4.6, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Elegant spring blooms', image: '',  stock: 25, description: 'A spring favorite in many gardens.' },
  { id: '108', name: 'Hydrangea', scientificName: 'Hydrangea macrophylla', price: 899, originalPrice: 1300, rating: 4.8, category: 'Outdoor', subCategory: 'Shrubs', benefits: 'Large clusters of flowers', image: '',  stock: 20, description: 'Changes color based on soil pH.' },
  { id: '109', name: 'Petunia', scientificName: 'Petunia × atkinsiana', price: 249, originalPrice: 400, rating: 4.5, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Prolific blooming all season', image: '',  stock: 80, description: 'Great for hanging baskets.' },
  { id: '110', name: 'Bougainvillea', scientificName: 'Bougainvillea spectabilis', price: 549, originalPrice: 800, rating: 4.7, category: 'Outdoor', subCategory: 'Climbers', benefits: 'Vibrant colors and drought tolerant', image: '',  stock: 30, description: 'A thorny ornamental vine.' },
  { id: '111', name: 'Gardenia', scientificName: 'Gardenia jasminoides', price: 799, originalPrice: 1100, rating: 4.8, category: 'Outdoor', subCategory: 'Fragrant', benefits: 'Exquisite fragrance and white blooms', image: '',  stock: 15, description: 'A symbol of purity and grace.' },
  { id: '112', name: 'Chrysanthemum', scientificName: 'Chrysanthemum', price: 349, originalPrice: 550, rating: 4.6, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Autumn color and long-lasting', image: '',  stock: 45, description: 'The "Queen of the Fall Flowers".' },
  { id: '113', name: 'Dahlia', scientificName: 'Dahlia', price: 499, originalPrice: 750, rating: 4.9, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Incredible variety of shapes', image: '',  stock: 20, description: 'A diverse and stunning garden plant.' },
  { id: '114', name: 'Zinnia', scientificName: 'Zinnia elegans', price: 199, originalPrice: 300, rating: 4.7, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Easy to grow from seed', image: '',  stock: 70, description: 'Attracts butterflies and hummingbirds.' },
  { id: '115', name: 'Pansy', scientificName: 'Viola tricolor hortensis', price: 149, originalPrice: 250, rating: 4.5, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Cheerful "faces" and cold hardy', image: '',  stock: 90, description: 'Perfect for winter and spring color.' },
  { id: '116', name: 'Geranium', scientificName: 'Pelargonium', price: 399, originalPrice: 600, rating: 4.7, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Classic garden favorite', image: '',  stock: 40, description: 'Great for pots and garden beds.' },
  { id: '117', name: 'Lantana', scientificName: 'Lantana camara', price: 299, originalPrice: 450, rating: 4.6, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Heat tolerant and attracts bees', image: '',  stock: 55, description: 'Clusters of small, colorful flowers.' },
  { id: '118', name: 'Salvia', scientificName: 'Salvia', price: 349, originalPrice: 500, rating: 4.8, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Spikes of vibrant color', image: '',  stock: 35, description: 'A member of the mint family.' },
  { id: '119', name: 'Verbena', scientificName: 'Verbena', price: 249, originalPrice: 400, rating: 4.5, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Trailing habit and long blooming', image: '',  stock: 65, description: 'Excellent groundcover or trailer.' },
  { id: '120', name: 'Vinca', scientificName: 'Catharanthus roseus', price: 199, originalPrice: 300, rating: 4.7, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Extremely heat and drought tolerant', image: '',  stock: 85, description: 'Also known as Periwinkle.' },
  { id: '121', name: 'Cosmos', scientificName: 'Cosmos bipinnatus', price: 149, originalPrice: 250, rating: 4.8, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Feathery foliage and airy blooms', image: '',  stock: 75, description: 'Easy to grow and self-seeds.' },
  { id: '122', name: 'Aster', scientificName: 'Aster', price: 349, originalPrice: 500, rating: 4.6, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Late season color', image: '',  stock: 40, description: 'Star-shaped flowers for the fall.' },
  { id: '123', name: 'Coreopsis', scientificName: 'Coreopsis', price: 299, originalPrice: 450, rating: 4.7, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Cheerful yellow blooms', image: '',  stock: 50, description: 'Commonly called Tickseed.' },
  { id: '124', name: 'Echinacea', scientificName: 'Echinacea purpurea', price: 449, originalPrice: 650, rating: 4.9, category: 'Outdoor', subCategory: 'Medicinal', benefits: 'Immune boosting and beautiful', image: '',  stock: 30, description: 'Also known as Purple Coneflower.' },
  { id: '125', name: 'Rudbeckia', scientificName: 'Rudbeckia hirta', price: 249, originalPrice: 400, rating: 4.8, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Iconic yellow and black blooms', image: '',  stock: 60, description: 'Black-eyed Susans are a garden staple.' },
  { id: '126', name: 'Gaillardia', scientificName: 'Gaillardia × grandiflora', price: 299, originalPrice: 450, rating: 4.7, category: 'Outdoor', subCategory: 'Sun-loving', benefits: 'Fiery red and yellow colors', image: '',  stock: 45, description: 'Commonly known as Blanket Flower.' },
  { id: '127', name: 'Daylily', scientificName: 'Hemerocallis', price: 599, originalPrice: 850, rating: 4.8, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Extremely hardy and reliable', image: '',  stock: 25, description: 'Each flower lasts only one day.' },
  { id: '128', name: 'Peony', scientificName: 'Paeonia', price: 1499, originalPrice: 2200, rating: 4.9, category: 'Outdoor', subCategory: 'Flowering', benefits: 'Huge, lush, fragrant blooms', image: '',  stock: 10, description: 'A long-lived garden treasure.' },
  { id: '129', name: 'Azalea', scientificName: 'Rhododendron', price: 899, originalPrice: 1300, rating: 4.7, category: 'Outdoor', subCategory: 'Shrubs', benefits: 'Explosion of spring color', image: '',  stock: 15, description: 'Loves acidic soil and partial shade.' },
  { id: '130', name: 'Bonsai Pine', scientificName: 'Pinus', price: 4999, originalPrice: 7500, rating: 4.9, category: 'Outdoor', subCategory: 'Bonsai', benefits: 'Artistic and meditative', image: '',  stock: 5, description: 'A miniature masterpiece.' },

  // Medicinal Plants
  { id: '201', name: 'Tulsi (Holy Basil)', scientificName: 'Ocimum tenuiflorum', price: 199, originalPrice: 300, rating: 4.9, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Boosts immunity and relieves stress', image: '',  stock: 100, description: 'The "Queen of Herbs" in India.' },
  { id: '202', name: 'Neem', scientificName: 'Azadirachta indica', price: 299, originalPrice: 450, rating: 4.8, category: 'Medicinal', subCategory: 'Trees', benefits: 'Antibacterial and skin healing', image: '',  stock: 50, description: 'Known as the "Village Pharmacy".' },
  { id: '203', name: 'Ashwagandha', scientificName: 'Withania somnifera', price: 399, originalPrice: 600, rating: 4.7, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Reduces anxiety and improves strength', image: '',  stock: 40, description: 'A powerful adaptogen.' },
  { id: '204', name: 'Turmeric', scientificName: 'Curcuma longa', price: 249, originalPrice: 400, rating: 4.8, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Anti-inflammatory and antioxidant', image: '',  stock: 60, description: 'The golden spice of life.' },
  { id: '205', name: 'Ginger', scientificName: 'Zingiber officinale', price: 149, originalPrice: 250, rating: 4.7, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Aids digestion and treats colds', image: '',  stock: 80, description: 'A versatile root with many uses.' },
  { id: '206', name: 'Lemongrass', scientificName: 'Cymbopogon', price: 199, originalPrice: 300, rating: 4.6, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Relieves pain and fever', image: '',  stock: 70, description: 'Fresh citrusy aroma and flavor.' },
  { id: '207', name: 'Peppermint', scientificName: 'Mentha × piperita', price: 249, originalPrice: 350, rating: 4.8, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Soothes stomach and refreshes breath', image: '',  stock: 55, description: 'Cooling and invigorating.' },
  { id: '208', name: 'Calendula', scientificName: 'Calendula officinalis', price: 299, originalPrice: 450, rating: 4.7, category: 'Medicinal', subCategory: 'Flowering', benefits: 'Heals wounds and skin irritation', image: '',  stock: 45, description: 'Also known as Pot Marigold.' },
  { id: '209', name: 'Chamomile', scientificName: 'Matricaria chamomilla', price: 349, originalPrice: 500, rating: 4.9, category: 'Medicinal', subCategory: 'Flowering', benefits: 'Promotes sleep and relaxation', image: '',  stock: 35, description: 'Famous for its calming tea.' },
  { id: '210', name: 'Stevia', scientificName: 'Stevia rebaudiana', price: 399, originalPrice: 600, rating: 4.6, category: 'Medicinal', subCategory: 'Herbs', benefits: 'Natural zero-calorie sweetener', image: '',  stock: 30, description: 'A natural sugar substitute plant.' },
];

const plantImages: Record<string, string> = import.meta.glob('./plantsimages/**/*.{jpg,jpeg,png,webp,avif}', { eager: true, import: 'default' });

export const PLANTS: Plant[] = rawPlants.map(plant => {
  let localImage = plant.image;
  for (const path in plantImages) {
    const parts = path.split('/');
    const filenameWithExt = parts[parts.length - 1];
    const filename = filenameWithExt.substring(0, filenameWithExt.lastIndexOf('.'));

    if (filename === plant.name) {
      localImage = plantImages[path];
      break;
    }
  }
  return {
    ...plant,
    ...(localImage ? { image: localImage } : {})
  };
});
